### ISSUE TITLE
p-autocomplete item overflow

### ISSUE THREAD

**Issue by rtweera** [HRS0986/iCMS-Frontend#113]
list item (or something) overflows, can't close a selected item.

**Comment by rtweera** [comment]
p-autocomplete uses li items for each item/tag. That was overflowing because in the normal rules, you can't wrap/break a word in the middle (i.e. typewriter can't be broken as type-writer).

Solution was to override the normal rules used in li

```scss
    :host ::ng-deep li {
        word-break: break-all;
    }
```
